# Site settings
title: Aleksandra Mokawska
url: "http://themakowska.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
who: Aleksandra Mokawska
what: CEO
where: Jelenia Gora, Poland
employer: XWP
employer_URI: https://xwp.co
email: aleks@blabla.com
email_encoded: "" # see http://rot13.com

work:
  - "blablabla for [Stream](http://wp-stream.com)."

# Build settings
markdown: kramdown
